export const appTypes = {};

export const authTypes = {
  SET_USER_DATA: "SET_USER_DATA",
};

export const userTypes = {
  LOADING: "LOADING",
  ERROR: "ERROR",
  FOLLOWING_IN_PROGRESS: "FOLLOWING_IN_PROGRESS",

  FOLLOW_USER: "FOLLOW_USER",
  UNFOLLOW_USER: "UNFOLLOW_USER",


  USER_SUCCEED: "USER_SUCCEED",

  SET_CURRENT_PAGE: "SET_CURRENT_PAGE",

  AUTH_SET_DATA: "AUTH_SET_DATA",
  AUTH_SUCCEED: "AUTH_SUCCESS"
};

export const postTypes = {
  ADD_NEW_POST: "ADD_NEW_POST",
  UPDATE_INPUT_POST_TEXT: "UPDATE_INPUT_POST_TEXT",
};

export const messageTypes = {
  ADD_NEW_MESSAGE: "ADD_NEW_MESSAGE",
};

export const profileTypes = {
  PROFILE_SET_DATA: "PROFILE_SET_DATA",
  PROFILE_SET_STATUS: "PROFILE_SET_STATUS",
  PROFILE_UPDATE_STATUS: "PROFILE_UPDATE_STATUS",
  PROFILE_ERROR_USER: "PROFILE_ERROR_USER",
  PROFILE_LOADING_USER: "PROFILE_LOADING_USER",
  PROFILE_LOADING_USER_STOP: "PROFILE_LOADING_USER_STOP",
};
